# PBS flags
queue: express
project: x77
walltime: 0:30:00
ncpus: 2
mem: 4GB
jobname: double_gyre
runspersub: 10

collate:
    walltime: 0:30:00
    mem: 1GB

# Model config
model: mom6
# model: gold
shortpath: /short/v45
exe: MOM6_opt
input: double_gyre
priority: 15
stacksize: unlimited 

runlog: true

postscript: ls.sh

manifest:
    scaninputs: False
