# PBS flags
queue: express
project: v45
walltime: 0:30:00
ncpus: 2
mem: 4GB
jobname: double_gyre
runspersub: 10

collate:
    enable: False
    restart: True
    walltime: 0:30:00
    mem: 1GB

# Model config
model: mom6
shortpath: /scratch/v45
exe: MOM6-25Jan2020
input: double_gyre
priority: 15
stacksize: unlimited 

repeat: True

runlog: true

userscripts:
     error: resub.sh
