format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /short/v45/aph502/mom6/archive/double_gyre_test/restart013/MOM.res.nc
  hashes:
    binhash: 9dad43f84abfb5c2b4acae463c69b846
    md5: 2eb4172a084a9fecfaf704cab993496f
work/INPUT/ocean_solo.res:
  fullpath: /short/v45/aph502/mom6/archive/double_gyre_test/restart013/ocean_solo.res
  hashes:
    binhash: 72214d9aa6e30f7b33d801b244d298b3
    md5: 1e55ba1801b9a066f1c13eb054de0624
