format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /short/v45/aph502/mom6/archive/double_gyre_test/restart017/MOM.res.nc
  hashes:
    binhash: 84d028ca70f99b39f5d8779c7035b417
    md5: 1b8941bf12f26c113e7e07e2af0bfc9b
work/INPUT/ocean_solo.res:
  fullpath: /short/v45/aph502/mom6/archive/double_gyre_test/restart017/ocean_solo.res
  hashes:
    binhash: 696e00775ac1379c3d0cd41ec6c9a843
    md5: d43265d7e151784a8d8e3dcd6eb30fa4
