format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /short/v45/aph502/mom6/archive/double_gyre_test/restart014/MOM.res.nc
  hashes:
    binhash: 248e3aee64febb2398934e92fa00854f
    md5: cd52e494a88087c0193607d0b268cfd3
work/INPUT/ocean_solo.res:
  fullpath: /short/v45/aph502/mom6/archive/double_gyre_test/restart014/ocean_solo.res
  hashes:
    binhash: daefc17901c8a4b014317bf8a8a322e0
    md5: f8833808f5cf95dc8bc3ec17c1422e13
