format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /short/v45/aph502/mom6/archive/double_gyre_test/restart002/MOM.res.nc
  hashes:
    binhash: 64be18571d3c5459a05a0ae9a9443145
    md5: 390330d0aaef6d7477247eab7f0140aa
work/INPUT/ocean_solo.res:
  fullpath: /short/v45/aph502/mom6/archive/double_gyre_test/restart002/ocean_solo.res
  hashes:
    binhash: bbf44a45675dce493c51d94b1ff04da7
    md5: 182c791bb7587ce53a51e53a6675d060
